/**
 * Module Constants.
 * Language strings and constants for the modules feature.
 */

export const MODULE_STRINGS = {
  en: {
    TITLE: "Modules",
    DESC: "Manage and configure modules for different roles",
    ADD_MODULE: "Add Module",
    CREATE_TITLE: "Create New Module",
    CREATE_DESC: "Fill in the details below to create a new module module",
    EDIT_TITLE: "Edit Module",
    EDIT_DESC: "Update the module configuration",
    LABEL_NAME: "Module Name",
    PLACEHOLDER_NAME: "e.g., Manage Users",
    LABEL_DESC: "Description",
    PLACEHOLDER_DESC: "Describe what this module allows...",
    LABEL_ICON: "Icon String",
    LABEL_ROUTE: "Route Path",
    LABEL_MODULES: "Applicable Modules",
    DESC_MODULES: "Select which modules this module applies to",
    TH_NAME: "Name",
    TH_STATUS: "Status",
    TH_ROUTE: "Route",
    TH_DESC: "Description",
    TH_CREATED: "Created Date",
    TH_ACTIONS: "Actions",
    NO_MODULES: "No modules found. Create your first one!",
    CANCEL: "Cancel",
    SAVING: "Saving...",
    SAVE_MODULE: "Save Module",
    BACK_TO_MODULES: "Back to Modules",
    TIPS: "Helpful Tips",
    TIP_1: "Use clear, descriptive names for modules.",
    TIP_2: "Group related modules together.",
    TIP_3: "Don't create overly granular modules unless necessary.",
    TIP_4: "Route paths must be lowercase, use hyphens (-) instead of spaces, and contain no capital letters.",
    ERR_NAME_MIN: "Name must be at least 2 characters",
    ERR_NAME_MAX: "Name cannot exceed 50 characters",
    ERR_NAME_REQ: "Module Name is required",
    ERR_DESC_MAX: "Description cannot exceed 500 characters",
    UNASSIGNED_ROUTES: "Unassigned Routes",
    LOADING_ROUTES: "Loading routes...",
    ALL_ROUTES_ASSIGNED: "All routes have modules assigned.",
    ROUTE_TIPS_TITLE: "Route Assignment Tips",
    ROUTE_TIPS_DESC_1: "The Route Path must exactly match your frontend route (e.g., /dashboard).",
    ROUTE_TIPS_DESC_2: "When creating a module, it auto-generates as you type the name, but you can manually edit it.",
    ROUTE_TIPS_DESC_3: "When editing an existing module, the route will not auto-update to prevent breaking existing assignments.",
    ROUTE_TIPS_NOTE_TITLE: "Note:",
    ROUTE_TIPS_GOT_IT: "Got it",
  },
  hi: {
    TITLE: "मॉड्यूल (Modules)",
    DESC: "विभिन्न भूमिकाओं के लिए मॉड्यूल प्रबंधित और कॉन्फ़िगर करें",
    ADD_MODULE: "मॉड्यूल जोड़ें",
    CREATE_TITLE: "नई मॉड्यूल बनाएं",
    CREATE_DESC: "नई मॉड्यूल बनाने के लिए नीचे विवरण भरें",
    EDIT_TITLE: "मॉड्यूल संपादित करें",
    EDIT_DESC: "मॉड्यूल कॉन्फ़िगरेशन अपडेट करें",
    LABEL_NAME: "मॉड्यूल का नाम",
    PLACEHOLDER_NAME: "उदा., उपयोगकर्ता प्रबंधित करें",
    LABEL_DESC: "विवरण",
    PLACEHOLDER_DESC: "वर्णन करें कि यह मॉड्यूल क्या करने देती है...",
    LABEL_ICON: "आइकन (Icon)",
    LABEL_ROUTE: "रूट पथ (Route Path)",
    LABEL_MODULES: "लागू मॉड्यूल",
    DESC_MODULES: "चुनें कि यह मॉड्यूल किन मॉड्यूल पर लागू होती है",
    TH_NAME: "नाम",
    TH_STATUS: "स्थिति",
    TH_ROUTE: "रूट (Route)",
    TH_DESC: "विवरण",
    TH_CREATED: "बनाए जाने की तिथि",
    TH_ACTIONS: "कार्रवाइयां",
    NO_MODULES: "कोई मॉड्यूल नहीं मिली। अपना पहला बनाएं!",
    CANCEL: "रद्द करें",
    SAVING: "सहेजा जा रहा है...",
    SAVE_MODULE: "मॉड्यूल सहेजें",
    BACK_TO_MODULES: "मॉड्यूल पर वापस जाएँ",
    TIPS: "मददगार सुझाव",
    TIP_1: "मॉड्यूल के लिए स्पष्ट, वर्णनात्मक नामों का उपयोग करें।",
    TIP_2: "संबंधित मॉड्यूल को एक साथ समूहित करें।",
    TIP_3: "अनावश्यक रूप से दानेदार मॉड्यूल न बनाएं।",
    TIP_4: "रूट पथ लोअरकेस में होने चाहिए, स्पेस की जगह हाइफ़न (-) का उपयोग करें, और कोई कैपिटल अक्षर न हो।",
    ERR_NAME_MIN: "नाम कम से कम 2 अक्षरों का होना चाहिए",
    ERR_NAME_MAX: "नाम 50 अक्षरों से अधिक नहीं हो सकता",
    ERR_NAME_REQ: "मॉड्यूल का नाम आवश्यक है",
    ERR_DESC_MAX: "विवरण 500 अक्षरों से अधिक नहीं हो सकता",
    UNASSIGNED_ROUTES: "असाइन नहीं किए गए रूट (Unassigned Routes)",
    LOADING_ROUTES: "रूट लोड हो रहे हैं...",
    ALL_ROUTES_ASSIGNED: "सभी रूट मॉड्यूल को असाइन कर दिए गए हैं।",
    ROUTE_TIPS_TITLE: "रूट असाइनमेंट टिप्स (Route Assignment Tips)",
    ROUTE_TIPS_DESC_1: "रूट पथ (Route Path) आपके फ्रंटएंड रूट (जैसे, /dashboard) से बिल्कुल मेल खाना चाहिए।",
    ROUTE_TIPS_DESC_2: "मॉड्यूल बनाते समय, जैसे ही आप नाम टाइप करते हैं यह स्वतः जनरेट हो जाता है, लेकिन आप इसे मैन्युअल रूप से भी संपादित कर सकते हैं।",
    ROUTE_TIPS_DESC_3: "मौजूदा मॉड्यूल को संपादित करते समय, मौजूदा असाइनमेंट को टूटने से बचाने के लिए रूट स्वतः अपडेट नहीं होगा।",
    ROUTE_TIPS_NOTE_TITLE: "नोट:",
    ROUTE_TIPS_GOT_IT: "समझ गया (Got it)",
  }
};
