import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/features/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#2e3039",
        "surface-variant": "#e1e2ed",
        "on-surface": "#191b23",
        "inverse-primary": "#b4c5ff",
        info: "#0EA5E9",
        "surface-dim": "#d9d9e5",
        "on-tertiary-fixed": "#191c1e",
        tertiary: "#525657",
        "on-secondary-container": "#5c647a",
        "surface-container": "#ededf9",
        "completion-progress": "#3B82F6",
        "surface-container-highest": "#e1e2ed",
        warning: "#F59E0B",
        "surface-container-lowest": "#ffffff",
        "on-tertiary": "#ffffff",
        "on-error-container": "#93000a",
        "tertiary-fixed-dim": "#c4c7c9",
        "on-primary-fixed": "#00174b",
        primary: "#004ac6",
        background: "#faf8ff",
        "tertiary-container": "#6b6e70",
        "inverse-on-surface": "#f0f0fb",
        success: "#10B981",
        "error-container": "#ffdad6",
        "on-background": "#191b23",
        "on-primary-container": "#eeefff",
        surface: "#faf8ff",
        "on-secondary-fixed": "#131b2e",
        "on-primary": "#ffffff",
        "on-tertiary-container": "#eff1f3",
        "on-surface-variant": "#434655",
        "secondary-fixed-dim": "#bec6e0",
        "surface-bright": "#faf8ff",
        "secondary-fixed": "#dae2fd",
        "on-error": "#ffffff",
        "primary-fixed": "#dbe1ff",
        secondary: "#565e74",
        "surface-container-high": "#e7e7f3",
        outline: "#737686",
        "surface-container-low": "#f3f3fe",
        "on-secondary": "#ffffff",
        "surface-tint": "#0053db",
        "on-primary-fixed-variant": "#003ea8",
        "primary-container": "#2563eb",
        "on-secondary-fixed-variant": "#3f465c",
        "on-tertiary-fixed-variant": "#444749",
        "secondary-container": "#dae2fd",
        "outline-variant": "#c3c6d7",
        "tertiary-fixed": "#e0e3e5",
        "primary-fixed-dim": "#b4c5ff",
        "surface-border": "#E2E8F0",
        error: "#EF4444",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "stack-gap-sm": "8px",
        "stack-gap-lg": "32px",
        "container-max-width": "1280px",
        "margin-mobile": "16px",
        "margin-desktop": "32px",
        unit: "4px",
        gutter: "24px",
        "stack-gap-md": "16px",
      },
      fontFamily: {
        "headline-md": ["Manrope"],
        "headline-lg-mobile": ["Manrope"],
        "headline-lg": ["Manrope"],
        "body-md": ["Inter"],
        "code-snippet": ["JetBrains Mono"],
        "label-caps": ["Inter"],
        "body-sm": ["Inter"],
        "body-lg": ["Inter"],
        "display-lg": ["Manrope"],
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "code-snippet": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "800" }],
      },
    },
  },
  plugins: [],
};

export default config;
