/**
 * Course Constants.
 */
export const COURSE_STRINGS = {
  en: {
    TITLE: "Courses",
    DESC: "Manage and configure courses",
    ADD_COURSE: "Add Course",
    CREATE_TITLE: "Create New Course",
    CREATE_DESC: "Fill in the details below to create a new course",
    EDIT_TITLE: "Edit Course",
    EDIT_DESC: "Update the course configuration",
    LABEL_CATEGORY: "Category",
    LABEL_TYPE: "Course Type",
    LABEL_LEVEL: "Level",
    LABEL_LANGUAGE: "Language",
    LABEL_STATUS: "Status",
    LABEL_SLUG: "Slug",
    LABEL_TITLE: "Course Title",
    LABEL_DESC: "Description",
    LABEL_OVERVIEW: "Overview",
    LABEL_PRICE: "Price",
    LABEL_DISCOUNT_PRICE: "Discount Price",
    TH_TITLE: "Title",
    TH_CATEGORY: "Category",
    TH_STATUS: "Status",
    TH_PRICE: "Price",
    TH_ACTIONS: "Actions",
    NO_COURSES: "No courses found. Create your first one!",
    CANCEL: "Cancel",
    SAVING: "Saving...",
    SAVE_COURSE: "Save Course",
    BACK_TO_COURSES: "Back to Courses",
    DETAILS_TITLE: "Course Details",
    VIEWING_DETAILS: "Viewing details for",
    NO_THUMBNAIL: "No Thumbnail",
    UNKNOWN: "Unknown",
    UNCATEGORIZED: "Uncategorized",
    NOT_SPECIFIED: "Not specified",
    GLOBAL: "Global",
    LABEL_CREATED: "Created",
    CONTENT_DETAILS: "Content Details",
    COVER_IMAGE: "Cover Image",
    PRICING_OFFERS: "Pricing & Offers",
    BASE_PRICE: "Base Price",
    NONE: "None",
    DISCOUNT_TYPE: "Discount Type",
    DISCOUNT_VALUE: "Discount Value",
    OFFER_STARTS: "Offer Starts",
    OFFER_ENDS: "Offer Ends",
    N_A: "N/A",
    NO_PRICING_INFO: "No pricing information available. This course might be completely free.",
    COURSE_TOPICS: "Course Topics",
    NO_TOPICS_ASSIGNED: "No topics assigned yet.",
    LOCALIZATION_DATA: "Localization Data",
    UNTITLED_COURSE: "Untitled Course",
    NO_DESC_PROVIDED: "No description provided.",
    NO_OVERVIEW_PROVIDED: "No overview provided.",
    NOT_FOUND: "Not found.",
  },
  hi: {
    TITLE: "कोर्स (Courses)",
    DESC: "पाठ्यक्रम प्रबंधित और कॉन्फ़िगर करें",
    ADD_COURSE: "कोर्स जोड़ें",
    CREATE_TITLE: "नया कोर्स बनाएं",
    CREATE_DESC: "नया कोर्स बनाने के लिए नीचे विवरण भरें",
    EDIT_TITLE: "कोर्स संपादित करें",
    EDIT_DESC: "कोर्स कॉन्फ़िगरेशन अपडेट करें",
    LABEL_CATEGORY: "श्रेणी",
    LABEL_TYPE: "कोर्स का प्रकार",
    LABEL_LEVEL: "स्तर",
    LABEL_LANGUAGE: "भाषा",
    LABEL_STATUS: "स्थिति",
    LABEL_SLUG: "स्लग",
    LABEL_TITLE: "कोर्स का शीर्षक",
    LABEL_DESC: "विवरण",
    LABEL_OVERVIEW: "अवलोकन",
    LABEL_PRICE: "कीमत",
    LABEL_DISCOUNT_PRICE: "छूट मूल्य",
    TH_TITLE: "शीर्षक",
    TH_CATEGORY: "श्रेणी",
    TH_STATUS: "स्थिति",
    TH_PRICE: "कीमत",
    TH_ACTIONS: "कार्रवाइयां",
    NO_COURSES: "कोई कोर्स नहीं मिले। अपना पहला बनाएं!",
    CANCEL: "रद्द करें",
    SAVING: "सहेजा जा रहा है...",
    SAVE_COURSE: "कोर्स सहेजें",
    BACK_TO_COURSES: "कोर्स पर वापस जाएँ",
    DETAILS_TITLE: "कोर्स विवरण",
    VIEWING_DETAILS: "के लिए विवरण देख रहे हैं",
    NO_THUMBNAIL: "कोई थंबनेल नहीं",
    UNKNOWN: "अज्ञात",
    UNCATEGORIZED: "अवर्गीकृत",
    NOT_SPECIFIED: "निर्दिष्ट नहीं है",
    GLOBAL: "वैश्विक",
    LABEL_CREATED: "बनाया गया",
    CONTENT_DETAILS: "सामग्री विवरण",
    COVER_IMAGE: "कवर छवि",
    PRICING_OFFERS: "मूल्य निर्धारण और प्रस्ताव",
    BASE_PRICE: "मूल कीमत",
    NONE: "कोई नहीं",
    DISCOUNT_TYPE: "छूट प्रकार",
    DISCOUNT_VALUE: "छूट मूल्य",
    OFFER_STARTS: "प्रस्ताव शुरू",
    OFFER_ENDS: "प्रस्ताव समाप्त",
    N_A: "लागू नहीं",
    NO_PRICING_INFO: "कोई मूल्य निर्धारण जानकारी उपलब्ध नहीं है। यह कोर्स पूरी तरह से मुफ्त हो सकता है।",
    COURSE_TOPICS: "कोर्स विषय",
    NO_TOPICS_ASSIGNED: "अभी तक कोई विषय निर्दिष्ट नहीं किया गया है।",
    LOCALIZATION_DATA: "स्थानीयकरण डेटा",
    UNTITLED_COURSE: "अनाम कोर्स",
    NO_DESC_PROVIDED: "कोई विवरण प्रदान नहीं किया गया।",
    NO_OVERVIEW_PROVIDED: "कोई अवलोकन प्रदान नहीं किया गया।",
    NOT_FOUND: "नहीं मिला।",
  }
};
