/**
 * Course Constants.
 */
export const COURSE_STRINGS = {
  en: {
    TITLE: "Courses",
    DESC: "Manage and configure courses",
    ADD_COURSE: "Add Course",
    CREATE_TITLE: "Create New Course",
    CREATE_DESC: "Fill in the details below to create a new course",
    EDIT_TITLE: "Edit Course",
    EDIT_DESC: "Update the course configuration",
    LABEL_CATEGORY: "Category",
    LABEL_TYPE: "Course Type",
    LABEL_LEVEL: "Level",
    LABEL_LANGUAGE: "Language",
    LABEL_STATUS: "Status",
    LABEL_SLUG: "Slug",
    LABEL_TITLE: "Course Title",
    LABEL_DESC: "Description",
    LABEL_OVERVIEW: "Overview",
    LABEL_PRICE: "Price",
    LABEL_DISCOUNT_PRICE: "Discount Price",
    TH_TITLE: "Title",
    TH_CATEGORY: "Category",
    TH_STATUS: "Status",
    TH_PRICE: "Price",
    TH_ACTIONS: "Actions",
    NO_COURSES: "No courses found. Create your first one!",
    CANCEL: "Cancel",
    SAVING: "Saving...",
    SAVE_COURSE: "Save Course",
    BACK_TO_COURSES: "Back to Courses",
  },
  hi: {
    TITLE: "कोर्स (Courses)",
    DESC: "पाठ्यक्रम प्रबंधित और कॉन्फ़िगर करें",
    ADD_COURSE: "कोर्स जोड़ें",
    CREATE_TITLE: "नया कोर्स बनाएं",
    CREATE_DESC: "नया कोर्स बनाने के लिए नीचे विवरण भरें",
    EDIT_TITLE: "कोर्स संपादित करें",
    EDIT_DESC: "कोर्स कॉन्फ़िगरेशन अपडेट करें",
    LABEL_CATEGORY: "श्रेणी",
    LABEL_TYPE: "कोर्स का प्रकार",
    LABEL_LEVEL: "स्तर",
    LABEL_LANGUAGE: "भाषा",
    LABEL_STATUS: "स्थिति",
    LABEL_SLUG: "स्लग",
    LABEL_TITLE: "कोर्स का शीर्षक",
    LABEL_DESC: "विवरण",
    LABEL_OVERVIEW: "अवलोकन",
    LABEL_PRICE: "कीमत",
    LABEL_DISCOUNT_PRICE: "छूट मूल्य",
    TH_TITLE: "शीर्षक",
    TH_CATEGORY: "श्रेणी",
    TH_STATUS: "स्थिति",
    TH_PRICE: "कीमत",
    TH_ACTIONS: "कार्रवाइयां",
    NO_COURSES: "कोई कोर्स नहीं मिले। अपना पहला बनाएं!",
    CANCEL: "रद्द करें",
    SAVING: "सहेजा जा रहा है...",
    SAVE_COURSE: "कोर्स सहेजें",
    BACK_TO_COURSES: "कोर्स पर वापस जाएँ",
  }
};
