/**
 * Feature Constants.
 * Defines constant values and translation strings used in the feature.
 */

export const USER_STRINGS = {
  en: {
    TITLE: "Users",
    DESC: "Manage platform users and their roles",
    ADD_USER: "Add User",
    TH_NAME: "Name",
    TH_EMAIL: "Email",
    TH_ROLE: "Role",
    TH_STATUS: "Status",
    TH_ACTIONS: "Actions",
    NO_USERS: "No users found.",
    EDIT_TITLE: "Edit User",
    EDIT_DESC: "Update the details of the user.",
    CREATE_TITLE: "Create New User",
    CREATE_DESC: "Add a new user to the platform.",
    SAVE_USER: "Save User",
    SAVING: "Saving...",
    LABEL_NAME: "Full Name",
    LABEL_EMAIL: "Email Address",
    LABEL_ROLE: "Role",
    LABEL_STATUS: "Status",
    PLACEHOLDER_NAME: "e.g. John Doe",
    PLACEHOLDER_EMAIL: "john@example.com",
    DETAILS_TITLE: "User Details",
    PROFILE_IMAGE: "Profile Image",
    UPLOAD_PICTURE: "Upload profile picture",
    IMAGE_HINT: "JPG, PNG or GIF. Max size 2MB.",
    CHOOSE_IMAGE: "Choose Image",
    USER_INFO: "User Information",
    LABEL_PHONE: "Phone Number",
    LABEL_PASSWORD: "Password",
    PLACEHOLDER_PASSWORD: "Enter password",
    LABEL_ABOUT: "About (Optional)",
    LABEL_ABOUT_VIEW: "About",
    PLACEHOLDER_ABOUT: "Add any additional details about this user...",
    DETAILS_DESC: "Detailed information and system access for",
    NO_ROLE: "No Role",
    NO_DETAILS: "No additional details provided.",
    LABEL_CREATED: "Created At",
    STATUS_ACTIVE: "Active",
    STATUS_INACTIVE: "Inactive",
    ADD_ROLE: "Add Role",
    CANCEL: "Cancel",
    BACK_TO_USERS: "Back to Users"
  },
  hi: {
    TITLE: "उपयोगकर्ता",
    DESC: "प्लेटफ़ॉर्म उपयोगकर्ताओं और उनकी भूमिकाओं का प्रबंधन करें",
    ADD_USER: "उपयोगकर्ता जोड़ें",
    TH_NAME: "नाम",
    TH_EMAIL: "ईमेल",
    TH_ROLE: "भूमिका",
    TH_STATUS: "स्थिति",
    TH_ACTIONS: "कार्रवाइयां",
    NO_USERS: "कोई उपयोगकर्ता नहीं मिला।",
    EDIT_TITLE: "उपयोगकर्ता संपादित करें",
    EDIT_DESC: "उपयोगकर्ता का विवरण अपडेट करें।",
    CREATE_TITLE: "नया उपयोगकर्ता बनाएँ",
    CREATE_DESC: "प्लेटफ़ॉर्म में एक नया उपयोगकर्ता जोड़ें।",
    SAVE_USER: "उपयोगकर्ता सहेजें",
    SAVING: "सहेजा जा रहा है...",
    LABEL_NAME: "पूरा नाम",
    LABEL_EMAIL: "ईमेल पता",
    LABEL_ROLE: "भूमिका",
    LABEL_STATUS: "स्थिति",
    PLACEHOLDER_NAME: "उदा. जॉन डो",
    PLACEHOLDER_EMAIL: "john@example.com",
    DETAILS_TITLE: "उपयोगकर्ता विवरण",
    PROFILE_IMAGE: "प्रोफ़ाइल छवि",
    UPLOAD_PICTURE: "प्रोफ़ाइल चित्र अपलोड करें",
    IMAGE_HINT: "JPG, PNG या GIF। अधिकतम आकार 2MB।",
    CHOOSE_IMAGE: "छवि चुनें",
    USER_INFO: "उपयोगकर्ता की जानकारी",
    LABEL_PHONE: "फ़ोन नंबर",
    LABEL_PASSWORD: "पासवर्ड",
    PLACEHOLDER_PASSWORD: "पासवर्ड दर्ज करें",
    LABEL_ABOUT: "के बारे में (वैकल्पिक)",
    LABEL_ABOUT_VIEW: "के बारे में",
    PLACEHOLDER_ABOUT: "इस उपयोगकर्ता के बारे में कोई अतिरिक्त विवरण जोड़ें...",
    DETAILS_DESC: "के लिए विस्तृत जानकारी और सिस्टम एक्सेस।",
    NO_ROLE: "कोई भूमिका नहीं",
    NO_DETAILS: "कोई अतिरिक्त विवरण नहीं दिया गया।",
    LABEL_CREATED: "बनाया गया",
    STATUS_ACTIVE: "सक्रिय",
    STATUS_INACTIVE: "निष्क्रिय",
    ADD_ROLE: "भूमिका जोड़ें",
    CANCEL: "रद्द करें",
    BACK_TO_USERS: "वापस लौटें"
  }
};
