/**
 * Feature Constants.
 * Defines constant values and translation strings used in the feature.
 */

export const USER_STRINGS = {
  en: {
    TITLE: "Users",
    DESC: "Manage platform users and their roles",
    ADD_USER: "Add User",
    TH_NAME: "Name",
    TH_EMAIL: "Email",
    TH_ROLE: "Role",
    TH_STATUS: "Status",
    TH_ACTIONS: "Actions",
    NO_USERS: "No users found.",
    EDIT_TITLE: "Edit User",
    EDIT_DESC: "Update the details of the user.",
    CREATE_TITLE: "Create New User",
    CREATE_DESC: "Add a new user to the platform.",
    SAVE_USER: "Save User",
    SAVING: "Saving...",
    LABEL_NAME: "Full Name",
    LABEL_EMAIL: "Email Address",
    LABEL_ROLE: "Role",
    LABEL_STATUS: "Status",
    PLACEHOLDER_NAME: "e.g. John Doe",
    PLACEHOLDER_EMAIL: "john@example.com",
    DETAILS_TITLE: "User Details",
    PROFILE_IMAGE: "Profile Image",
    UPLOAD_PICTURE: "Upload profile picture",
    IMAGE_HINT: "JPG, PNG or GIF. Max size 2MB.",
    CHOOSE_IMAGE: "Choose Image",
    USER_INFO: "User Information",
    LABEL_PHONE: "Phone Number",
    LABEL_PASSWORD: "Password",
    PLACEHOLDER_PASSWORD: "Enter password",
    LABEL_ABOUT: "About (Optional)",
    LABEL_ABOUT_VIEW: "About",
    PLACEHOLDER_ABOUT: "Add any additional details about this user...",
    DETAILS_DESC: "Detailed information and system access for",
    NO_ROLE: "No Role",
    NO_DETAILS: "No additional details provided.",
    LABEL_CREATED: "Created At",
    STATUS_ACTIVE: "Active",
    STATUS_INACTIVE: "Inactive",
    ADD_ROLE: "Add Role",
    CANCEL: "Cancel",
    BACK_TO_USERS: "Back to Users",
    LABEL_GENDER: "Gender",
    LABEL_DOB: "Date of Birth",
    LABEL_EXPERIENCE: "Experience (Years)",
    LABEL_LANGUAGES: "Languages (Comma separated)",
    LABEL_QUALIFICATION: "Qualification",
    LABEL_DEGREE: "Degree",
    LABEL_GRAD_YEAR: "Graduation Year",
    LABEL_ADDRESS: "Address",
    LABEL_CITY: "City",
    LABEL_COUNTRY: "Country",
    LABEL_WORK_EXPERIENCE: "Work Experience",
    LABEL_COMPANY: "Company",
    LABEL_JOB_TITLE: "Job Title",
    PLACEHOLDER_EXPERIENCE: "e.g. 5",
    PLACEHOLDER_LANGUAGES: "e.g. English, Hindi",
    PLACEHOLDER_DEGREE: "e.g. CS",
    PLACEHOLDER_YEAR: "e.g. 2018",
    PLACEHOLDER_CITY: "e.g. Noida",
    PLACEHOLDER_COUNTRY: "e.g. India",
    PLACEHOLDER_COMPANY: "e.g. Google",
    PLACEHOLDER_TITLE: "e.g. Engineer",
    SELECT_ROLE: "Select a role",
    OPTION_MALE: "Male",
    OPTION_FEMALE: "Female",
    OPTION_OTHER: "Other",
    ACCESS_LEVEL: "Access Level",
    PERMISSIONS: "Permissions",
    TWO_FACTOR_AUTH: "Two Factor Auth",
    LIMITED: "Limited",
    DISABLED: "Disabled",
    MANAGE_ACCESS: "Manage Access",
    USER_ID: "User ID",
    ACCOUNT_STATUS: "Account Status",
    LAST_LOGIN: "Last Login",
    NEVER: "Never"
  },
  hi: {
    TITLE: "उपयोगकर्ता",
    DESC: "प्लेटफ़ॉर्म उपयोगकर्ताओं और उनकी भूमिकाओं का प्रबंधन करें",
    ADD_USER: "उपयोगकर्ता जोड़ें",
    TH_NAME: "नाम",
    TH_EMAIL: "ईमेल",
    TH_ROLE: "भूमिका",
    TH_STATUS: "स्थिति",
    TH_ACTIONS: "कार्रवाइयां",
    NO_USERS: "कोई उपयोगकर्ता नहीं मिला।",
    EDIT_TITLE: "उपयोगकर्ता संपादित करें",
    EDIT_DESC: "उपयोगकर्ता का विवरण अपडेट करें।",
    CREATE_TITLE: "नया उपयोगकर्ता बनाएँ",
    CREATE_DESC: "प्लेटफ़ॉर्म में एक नया उपयोगकर्ता जोड़ें।",
    SAVE_USER: "उपयोगकर्ता सहेजें",
    SAVING: "सहेजा जा रहा है...",
    LABEL_NAME: "पूरा नाम",
    LABEL_EMAIL: "ईमेल पता",
    LABEL_ROLE: "भूमिका",
    LABEL_STATUS: "स्थिति",
    PLACEHOLDER_NAME: "उदा. जॉन डो",
    PLACEHOLDER_EMAIL: "john@example.com",
    DETAILS_TITLE: "उपयोगकर्ता विवरण",
    PROFILE_IMAGE: "प्रोफ़ाइल छवि",
    UPLOAD_PICTURE: "प्रोफ़ाइल चित्र अपलोड करें",
    IMAGE_HINT: "JPG, PNG या GIF। अधिकतम आकार 2MB।",
    CHOOSE_IMAGE: "छवि चुनें",
    USER_INFO: "उपयोगकर्ता की जानकारी",
    LABEL_PHONE: "फ़ोन नंबर",
    LABEL_PASSWORD: "पासवर्ड",
    PLACEHOLDER_PASSWORD: "पासवर्ड दर्ज करें",
    LABEL_ABOUT: "के बारे में (वैकल्पिक)",
    LABEL_ABOUT_VIEW: "के बारे में",
    PLACEHOLDER_ABOUT: "इस उपयोगकर्ता के बारे में कोई अतिरिक्त विवरण जोड़ें...",
    DETAILS_DESC: "के लिए विस्तृत जानकारी और सिस्टम एक्सेस।",
    NO_ROLE: "कोई भूमिका नहीं",
    NO_DETAILS: "कोई अतिरिक्त विवरण नहीं दिया गया।",
    LABEL_CREATED: "बनाया गया",
    STATUS_ACTIVE: "सक्रिय",
    STATUS_INACTIVE: "निष्क्रिय",
    ADD_ROLE: "भूमिका जोड़ें",
    CANCEL: "रद्द करें",
    BACK_TO_USERS: "वापस लौटें",
    LABEL_GENDER: "लिंग",
    LABEL_DOB: "जन्म तिथि",
    LABEL_EXPERIENCE: "अनुभव (वर्ष)",
    LABEL_LANGUAGES: "भाषाएँ (अल्पविराम द्वारा अलग)",
    LABEL_QUALIFICATION: "योग्यता",
    LABEL_DEGREE: "डिग्री",
    LABEL_GRAD_YEAR: "स्नातक वर्ष",
    LABEL_ADDRESS: "पता",
    LABEL_CITY: "शहर",
    LABEL_COUNTRY: "देश",
    LABEL_WORK_EXPERIENCE: "कार्य अनुभव",
    LABEL_COMPANY: "कंपनी",
    LABEL_JOB_TITLE: "नौकरी का शीर्षक",
    PLACEHOLDER_EXPERIENCE: "उदा. 5",
    PLACEHOLDER_LANGUAGES: "उदा. अंग्रेजी, हिंदी",
    PLACEHOLDER_DEGREE: "उदा. सीएस",
    PLACEHOLDER_YEAR: "उदा. 2018",
    PLACEHOLDER_CITY: "उदा. नोएडा",
    PLACEHOLDER_COUNTRY: "उदा. भारत",
    PLACEHOLDER_COMPANY: "उदा. गूगल",
    PLACEHOLDER_TITLE: "उदा. इंजीनियर",
    SELECT_ROLE: "भूमिका चुनें",
    OPTION_MALE: "पुरुष",
    OPTION_FEMALE: "महिला",
    OPTION_OTHER: "अन्य",
    ACCESS_LEVEL: "पहुँच स्तर",
    PERMISSIONS: "अनुमतियां",
    TWO_FACTOR_AUTH: "दो कारक प्रमाणीकरण",
    LIMITED: "सीमित",
    DISABLED: "अक्षम",
    MANAGE_ACCESS: "पहुँच प्रबंधित करें",
    USER_ID: "उपयोगकर्ता आईडी",
    ACCOUNT_STATUS: "खाता स्थिति",
    LAST_LOGIN: "अंतिम लॉगिन",
    NEVER: "कभी नहीं"
  }
};
