/**
 * Permission Constants.
 * Language strings and constants for the permissions feature.
 */

export const PERMISSION_STRINGS = {
  en: {
    TITLE: "Permissions",
    DESC: "Manage and configure permissions for different roles",
    ADD_PERMISSION: "Add Permission",
    CREATE_TITLE: "Create New Permission",
    CREATE_DESC: "Fill in the details below to create a new permission module",
    EDIT_TITLE: "Edit Permission",
    EDIT_DESC: "Update the permission configuration",
    LABEL_NAME: "Permission Name",
    PLACEHOLDER_NAME: "e.g., Manage Users",
    LABEL_DESC: "Description",
    PLACEHOLDER_DESC: "Describe what this permission allows...",
    LABEL_MODULES: "Applicable Modules",
    DESC_MODULES: "Select which modules this permission applies to",
    TH_NAME: "Name",
    TH_DESC: "Description",
    TH_CREATED: "Created Date",
    TH_ACTIONS: "Actions",
    NO_PERMISSIONS: "No permissions found. Create your first one!",
    CANCEL: "Cancel",
    SAVING: "Saving...",
    SAVE_PERMISSION: "Save Permission",
    BACK_TO_PERMISSIONS: "Back to Permissions",
    TIPS: "Helpful Tips",
    TIP_1: "Use clear, descriptive names for permissions.",
    TIP_2: "Group related permissions together.",
    TIP_3: "Don't create overly granular permissions unless necessary.",
    ERR_NAME_MIN: "Name must be at least 2 characters",
    ERR_NAME_MAX: "Name cannot exceed 50 characters",
    ERR_NAME_REQ: "Permission Name is required",
    ERR_DESC_MAX: "Description cannot exceed 500 characters",
    LABEL_CODE: "Permission Code",
    DESC_CODE: "A unique identifier used for backend checks (e.g. manage-users)",
    PLACEHOLDER_CODE: "e.g., manage-users",
    CODE_TIPS_TITLE: "Code Best Practices",
    CODE_TIPS_DESC_1: "The <strong>Permission Code</strong> is a stable identifier for developers. It should ideally be in <code>kebab-case</code> (e.g. <code>manage-users</code>, <code>view-reports</code>).",
    CODE_TIPS_DESC_2: "Once created and used in the codebase, you should avoid changing it, as it might break existing permission checks.",
    CODE_TIPS_NOTE_TITLE: "Auto-Generation",
    CODE_TIPS_NOTE_DESC: "When creating a new permission, the code is auto-generated from the English name to save time.",
    CODE_TIPS_GOT_IT: "Got it",
  },
  hi: {
    TITLE: "अनुमतियां (Permissions)",
    DESC: "विभिन्न भूमिकाओं के लिए अनुमतियां प्रबंधित और कॉन्फ़िगर करें",
    ADD_PERMISSION: "अनुमति जोड़ें",
    CREATE_TITLE: "नई अनुमति बनाएं",
    CREATE_DESC: "नई अनुमति बनाने के लिए नीचे विवरण भरें",
    EDIT_TITLE: "अनुमति संपादित करें",
    EDIT_DESC: "अनुमति कॉन्फ़िगरेशन अपडेट करें",
    LABEL_NAME: "अनुमति का नाम",
    PLACEHOLDER_NAME: "उदा., उपयोगकर्ता प्रबंधित करें",
    LABEL_DESC: "विवरण",
    PLACEHOLDER_DESC: "वर्णन करें कि यह अनुमति क्या करने देती है...",
    LABEL_MODULES: "लागू मॉड्यूल",
    DESC_MODULES: "चुनें कि यह अनुमति किन मॉड्यूल पर लागू होती है",
    TH_NAME: "नाम",
    TH_DESC: "विवरण",
    TH_CREATED: "बनाए जाने की तिथि",
    TH_ACTIONS: "कार्रवाइयां",
    NO_PERMISSIONS: "कोई अनुमति नहीं मिली। अपना पहला बनाएं!",
    CANCEL: "रद्द करें",
    SAVING: "सहेजा जा रहा है...",
    SAVE_PERMISSION: "अनुमति सहेजें",
    BACK_TO_PERMISSIONS: "अनुमतियों पर वापस जाएँ",
    TIPS: "मददगार सुझाव",
    TIP_1: "अनुमतियों के लिए स्पष्ट, वर्णनात्मक नामों का उपयोग करें।",
    TIP_2: "संबंधित अनुमतियों को एक साथ समूहित करें।",
    TIP_3: "अनावश्यक रूप से दानेदार अनुमतियां न बनाएं।",
    ERR_NAME_MIN: "नाम कम से कम 2 अक्षरों का होना चाहिए",
    ERR_NAME_MAX: "नाम 50 अक्षरों से अधिक नहीं हो सकता",
    ERR_NAME_REQ: "अनुमति का नाम आवश्यक है",
    ERR_DESC_MAX: "विवरण 500 अक्षरों से अधिक नहीं हो सकता",
    LABEL_CODE: "अनुमति कोड (Permission Code)",
    DESC_CODE: "बैकएंड जांच के लिए उपयोग किया जाने वाला एक विशिष्ट पहचानकर्ता (उदा. manage-users)",
    PLACEHOLDER_CODE: "उदा., manage-users",
    CODE_TIPS_TITLE: "कोड सर्वोत्तम अभ्यास",
    CODE_TIPS_DESC_1: "<strong>Permission Code</strong> डेवलपर्स के लिए एक स्थिर पहचानकर्ता है। इसे आदर्श रूप से <code>kebab-case</code> (उदा. <code>manage-users</code>, <code>view-reports</code>) में होना चाहिए।",
    CODE_TIPS_DESC_2: "एक बार बनाए जाने और कोडबेस में उपयोग किए जाने के बाद, आपको इसे बदलने से बचना चाहिए, क्योंकि यह मौजूदा अनुमति जांच को तोड़ सकता है।",
    CODE_TIPS_NOTE_TITLE: "स्वतः-उत्पादन (Auto-Generation)",
    CODE_TIPS_NOTE_DESC: "नई अनुमति बनाते समय, समय बचाने के लिए अंग्रेजी नाम से कोड स्वतः उत्पन्न हो जाता है।",
    CODE_TIPS_GOT_IT: "समझ गया",
  }
};
