/**
 * Permission Constants.
 * Language strings and constants for the permissions feature.
 */

export const PERMISSION_STRINGS = {
  en: {
    TITLE: "Permissions",
    DESC: "Manage and configure permissions for different roles",
    ADD_PERMISSION: "Add Permission",
    CREATE_TITLE: "Create New Permission",
    CREATE_DESC: "Fill in the details below to create a new permission module",
    EDIT_TITLE: "Edit Permission",
    EDIT_DESC: "Update the permission configuration",
    LABEL_NAME: "Permission Name",
    PLACEHOLDER_NAME: "e.g., Manage Users",
    LABEL_DESC: "Description",
    PLACEHOLDER_DESC: "Describe what this permission allows...",
    LABEL_MODULES: "Applicable Modules",
    DESC_MODULES: "Select which modules this permission applies to",
    TH_NAME: "Name",
    TH_DESC: "Description",
    TH_CREATED: "Created Date",
    TH_ACTIONS: "Actions",
    NO_PERMISSIONS: "No permissions found. Create your first one!",
    CANCEL: "Cancel",
    SAVING: "Saving...",
    SAVE_PERMISSION: "Save Permission",
    BACK_TO_PERMISSIONS: "Back to Permissions",
    TIPS: "Helpful Tips",
    TIP_1: "Use clear, descriptive names for permissions.",
    TIP_2: "Group related permissions together.",
    TIP_3: "Don't create overly granular permissions unless necessary.",
    ERR_NAME_MIN: "Name must be at least 2 characters",
    ERR_NAME_MAX: "Name cannot exceed 50 characters",
    ERR_NAME_REQ: "Permission Name is required",
    ERR_DESC_MAX: "Description cannot exceed 500 characters",
  },
  hi: {
    TITLE: "अनुमतियां (Permissions)",
    DESC: "विभिन्न भूमिकाओं के लिए अनुमतियां प्रबंधित और कॉन्फ़िगर करें",
    ADD_PERMISSION: "अनुमति जोड़ें",
    CREATE_TITLE: "नई अनुमति बनाएं",
    CREATE_DESC: "नई अनुमति बनाने के लिए नीचे विवरण भरें",
    EDIT_TITLE: "अनुमति संपादित करें",
    EDIT_DESC: "अनुमति कॉन्फ़िगरेशन अपडेट करें",
    LABEL_NAME: "अनुमति का नाम",
    PLACEHOLDER_NAME: "उदा., उपयोगकर्ता प्रबंधित करें",
    LABEL_DESC: "विवरण",
    PLACEHOLDER_DESC: "वर्णन करें कि यह अनुमति क्या करने देती है...",
    LABEL_MODULES: "लागू मॉड्यूल",
    DESC_MODULES: "चुनें कि यह अनुमति किन मॉड्यूल पर लागू होती है",
    TH_NAME: "नाम",
    TH_DESC: "विवरण",
    TH_CREATED: "बनाए जाने की तिथि",
    TH_ACTIONS: "कार्रवाइयां",
    NO_PERMISSIONS: "कोई अनुमति नहीं मिली। अपना पहला बनाएं!",
    CANCEL: "रद्द करें",
    SAVING: "सहेजा जा रहा है...",
    SAVE_PERMISSION: "अनुमति सहेजें",
    BACK_TO_PERMISSIONS: "अनुमतियों पर वापस जाएँ",
    TIPS: "मददगार सुझाव",
    TIP_1: "अनुमतियों के लिए स्पष्ट, वर्णनात्मक नामों का उपयोग करें।",
    TIP_2: "संबंधित अनुमतियों को एक साथ समूहित करें।",
    TIP_3: "अनावश्यक रूप से दानेदार अनुमतियां न बनाएं।",
    ERR_NAME_MIN: "नाम कम से कम 2 अक्षरों का होना चाहिए",
    ERR_NAME_MAX: "नाम 50 अक्षरों से अधिक नहीं हो सकता",
    ERR_NAME_REQ: "अनुमति का नाम आवश्यक है",
    ERR_DESC_MAX: "विवरण 500 अक्षरों से अधिक नहीं हो सकता",
  }
};
