/**
 * Feature Constants.
 * Defines constant values and translation strings used in the feature.
 */

export const ROLE_STRINGS = {
  en: {
    TITLE: "Roles",
    DESC: "Manage user roles and permissions",
    ADD_ROLE: "Add Role",
    TH_NAME: "Role Name",
    TH_DESC: "Description",
    TH_CREATED: "Created At",
    TH_ACTIONS: "Actions",
    NO_ROLES: "No roles found.",
    EDIT_TITLE: "Edit Role",
    EDIT_DESC: "Update the details of the role.",
    CREATE_TITLE: "Create New Role",
    CREATE_DESC: "Add a new role to the system.",
    SAVE_ROLE: "Save Role",
    SAVING: "Saving...",
    LABEL_NAME: "Role Name",
    LABEL_DESC: "Description",
    PLACEHOLDER_NAME: "e.g. Administrator",
    PLACEHOLDER_DESC: "Describe the permissions for this role",
    BACK_TO_ROLES: "Back to Roles",
    CREATE_NEW_ROLE_DESC: "Create a new role and assign permissions to control user access.",
    LABEL_PERMISSIONS: "Permissions",
    DESC_PERMISSIONS: "Select the permissions for this role",
    TH_MODULE: "Module",
    TH_VIEW: "View",
    TH_CREATE: "Create",
    TH_EDIT: "Edit",
    TH_DELETE: "Delete",
    TH_MANAGE: "Manage",
    CANCEL: "Cancel",
    TIPS: "Tips",
    TIP_1: "Role names should be unique",
    TIP_2: "Assign only required permissions",
    TIP_3: "Roles can be edited later"
  },
  hi: {
    TITLE: "भूमिकाएँ",
    DESC: "उपयोगकर्ता भूमिकाओं और अनुमतियों का प्रबंधन करें",
    ADD_ROLE: "भूमिका जोड़ें",
    TH_NAME: "भूमिका का नाम",
    TH_DESC: "विवरण",
    TH_CREATED: "बनाया गया",
    TH_ACTIONS: "कार्रवाइयां",
    NO_ROLES: "कोई भूमिका नहीं मिली।",
    EDIT_TITLE: "भूमिका संपादित करें",
    EDIT_DESC: "भूमिका के विवरण अपडेट करें।",
    CREATE_TITLE: "नई भूमिका बनाएँ",
    CREATE_DESC: "सिस्टम में एक नई भूमिका जोड़ें।",
    SAVE_ROLE: "भूमिका सहेजें",
    SAVING: "सहेजा जा रहा है...",
    LABEL_NAME: "भूमिका का नाम",
    LABEL_DESC: "विवरण",
    PLACEHOLDER_NAME: "उदा. व्यवस्थापक",
    PLACEHOLDER_DESC: "इस भूमिका के लिए अनुमतियों का वर्णन करें",
    BACK_TO_ROLES: "भूमिकाओं पर वापस लौटें",
    CREATE_NEW_ROLE_DESC: "एक नई भूमिका बनाएँ और उपयोगकर्ता पहुंच को नियंत्रित करने के लिए अनुमतियां असाइन करें।",
    LABEL_PERMISSIONS: "अनुमतियाँ",
    DESC_PERMISSIONS: "इस भूमिका के लिए अनुमतियां चुनें",
    TH_MODULE: "मॉड्यूल",
    TH_VIEW: "देखें",
    TH_CREATE: "बनाएं",
    TH_EDIT: "संपादित करें",
    TH_DELETE: "हटाएं",
    TH_MANAGE: "प्रबंधित करें",
    CANCEL: "रद्द करें",
    TIPS: "सुझाव",
    TIP_1: "भूमिका के नाम अद्वितीय होने चाहिए",
    TIP_2: "केवल आवश्यक अनुमतियां असाइन करें",
    TIP_3: "भूमिकाओं को बाद में संपादित किया जा सकता है"
  }
};
