/**
 * Course Category Constants.
 * Language strings and constants for the course categories feature.
 */

export const COURSE_CATEGORY_STRINGS = {
  en: {
    TITLE: "Course Categories",
    DESC: "Manage and configure course categories",
    ADD_CATEGORY: "Add Category",
    CREATE_TITLE: "Create New Category",
    CREATE_DESC: "Fill in the details below to create a new course category",
    EDIT_TITLE: "Edit Category",
    EDIT_DESC: "Update the category configuration",
    LABEL_TITLE: "Category Title",
    PLACEHOLDER_TITLE: "e.g., Web Development",
    LABEL_DESC: "Description",
    PLACEHOLDER_DESC: "Describe what this category is about...",
    TH_TITLE: "Title",
    TH_STATUS: "Status",
    TH_DESC: "Description",
    TH_CREATED: "Created Date",
    TH_ACTIONS: "Actions",
    NO_CATEGORIES: "No categories found. Create your first one!",
    CANCEL: "Cancel",
    SAVING: "Saving...",
    SAVE_CATEGORY: "Save Category",
    BACK_TO_CATEGORIES: "Back to Categories",
    DETAILS_TITLE: "Category Details",
    VIEWING_DETAILS: "Viewing details for",
    ACTIVE: "Active",
    INACTIVE: "Inactive",
    HIERARCHY: "Hierarchy",
    SUB_CATEGORY: "Sub-Category",
    ROOT_CATEGORY: "Root Category",
    LABEL_CREATED: "Created",
    LAST_UPDATED: "Last Updated",
    CATEGORY_INFO: "Category Information",
    PARENT_CATEGORY: "Parent Category",
    CATEGORY_NAME: "Category Name",
    AUDIT_TRAIL: "Audit Trail",
    CREATED_BY: "Created By (User ID)",
    LAST_UPDATED_BY: "Last Updated By (User ID)",
    LOCALIZATION_DATA: "Localization Data",
    LABEL_LANGUAGE: "Language",
    UNTITLED_CATEGORY: "Untitled Category",
    NO_DESC_PROVIDED: "No description provided.",
    NOT_FOUND: "Not found.",
    TIPS: "Helpful Tips",
    TIP_1: "Use clear, descriptive names for categories.",
    TIP_2: "Group related courses under appropriate categories.",
    TIP_3: "Add a helpful description in both English and Hindi.",
    ERR_TITLE_MIN: "Title must be at least 2 characters",
    ERR_TITLE_MAX: "Title cannot exceed 100 characters",
    ERR_TITLE_REQ: "Category Title is required",
    ERR_DESC_MAX: "Description cannot exceed 500 characters",
  },
  hi: {
    TITLE: "कोर्स श्रेणियां (Course Categories)",
    DESC: "कोर्स श्रेणियों को प्रबंधित और कॉन्फ़िगर करें",
    ADD_CATEGORY: "श्रेणी जोड़ें",
    CREATE_TITLE: "नई श्रेणी बनाएं",
    CREATE_DESC: "नई श्रेणी बनाने के लिए नीचे विवरण भरें",
    EDIT_TITLE: "श्रेणी संपादित करें",
    EDIT_DESC: "श्रेणी कॉन्फ़िगरेशन अपडेट करें",
    LABEL_TITLE: "श्रेणी का शीर्षक",
    PLACEHOLDER_TITLE: "उदा., वेब विकास",
    LABEL_DESC: "विवरण",
    PLACEHOLDER_DESC: "वर्णन करें कि यह श्रेणी किस बारे में है...",
    TH_TITLE: "शीर्षक",
    TH_STATUS: "स्थिति",
    TH_DESC: "विवरण",
    TH_CREATED: "बनाए जाने की तिथि",
    TH_ACTIONS: "कार्रवाइयां",
    NO_CATEGORIES: "कोई श्रेणियां नहीं मिलीं। अपना पहला बनाएं!",
    CANCEL: "रद्द करें",
    SAVING: "सहेजा जा रहा है...",
    SAVE_CATEGORY: "श्रेणी सहेजें",
    BACK_TO_CATEGORIES: "श्रेणियों पर वापस जाएँ",
    DETAILS_TITLE: "श्रेणी विवरण",
    VIEWING_DETAILS: "के लिए विवरण देख रहे हैं",
    ACTIVE: "सक्रिय",
    INACTIVE: "निष्क्रिय",
    HIERARCHY: "पदानुक्रम",
    SUB_CATEGORY: "उप-श्रेणी",
    ROOT_CATEGORY: "रूट श्रेणी",
    LABEL_CREATED: "बनाया गया",
    LAST_UPDATED: "अंतिम बार अपडेट किया गया",
    CATEGORY_INFO: "श्रेणी की जानकारी",
    PARENT_CATEGORY: "मूल श्रेणी",
    CATEGORY_NAME: "श्रेणी का नाम",
    AUDIT_TRAIL: "ऑडिट ट्रेल",
    CREATED_BY: "द्वारा निर्मित (उपयोगकर्ता आईडी)",
    LAST_UPDATED_BY: "अंतिम बार अपडेट किया गया (उपयोगकर्ता आईडी)",
    LOCALIZATION_DATA: "स्थानीयकरण डेटा",
    LABEL_LANGUAGE: "भाषा",
    UNTITLED_CATEGORY: "अनाम श्रेणी",
    NO_DESC_PROVIDED: "कोई विवरण प्रदान नहीं किया गया।",
    NOT_FOUND: "नहीं मिला।",
    TIPS: "Helpful Tips",
    TIP_1: "श्रेणियों के लिए स्पष्ट, वर्णनात्मक नामों का उपयोग करें।",
    TIP_2: "संबंधित पाठ्यक्रमों को उचित श्रेणियों के अंतर्गत समूहित करें।",
    TIP_3: "अंग्रेजी और हिंदी दोनों में एक उपयोगी विवरण जोड़ें।",
    ERR_TITLE_MIN: "शीर्षक कम से कम 2 अक्षरों का होना चाहिए",
    ERR_TITLE_MAX: "शीर्षक 100 अक्षरों से अधिक नहीं हो सकता",
    ERR_TITLE_REQ: "श्रेणी का शीर्षक आवश्यक है",
    ERR_DESC_MAX: "विवरण 500 अक्षरों से अधिक नहीं हो सकता",
  }
};
